### ISSUE TITLE
Add me as a maintainer 

### ISSUE THREAD

**Issue by pi0neerpat** [bekatom/awesome-ethereum#20]
This list is dead, and needs new life!

I am an active developer in the space, I wont merge bullshit projects or scams, and I am also a maintainer of the ConsenSys ethereum-tools list.

Thanks!

**Comment by bonedaddy** [comment]
+1 for having pi0neerpat as maintainer couldn't have a more solid person as maintainer for this.

**Comment by bekatom** [comment]
Sory @pi0neerpat  for a very late reply. An invitation has been sent!

**Comment by pi0neerpat** [comment]
<3
